spring:
  datasource:
    url: jdbc:h2:file:./target/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
graphql:
      servlet:
               mapping: /graphql
               enabled: true
               corsEnabled: true
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL